app_for_testing/i-rock/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :achievements
  
  root to: 'welcome#index'
end

app_for_testing/i-rock/app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :user, optional: true

  validates :title, presence: true
  validates :user, presence:true
  validates :title, uniqueness: {
    scope: :user_id,
    message: "you can't have two achievements with the same title"
  }

  enum privacy: [ :public_access, :private_access, :friends_access ]

  def description_html
    Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(description)
  end

  def silly_title
    "#{title} by #{user.email}"
  end

  def self.by_letter(letter)
    includes(:user).where("title LIKE ?", "#{letter}%").order("users.email ASC")
  end
end

app_for_testing/i-rock/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app_for_testing/i-rock/app/models/user.rb
class User < ApplicationRecord
  has_many :achievements
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app_for_testing/i-rock/app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy ]
  before_action :owners_only, only: [:edit, :update, :destroy]

  def index
    @achievements = Achievement.public_access
  end

  def new
    @achievement = Achievement.new
  end

  def create
    @achievement = Achievement.new(achievement_params)
    if @achievement.save
      redirect_to achievement_url(@achievement), notice: "Achievement has been created"
    else
      render :new
    end
  end

  def update   
    if @achievement.update(achievement_params)
      redirect_to achievement_url(@achievement), notice: "Achievement has been updated"
    else
      render :edit
    end
  end

  def edit
  end

  def show
    @achievement = Achievement.find(params[:id])
  end

  def destroy
    @achievement.destroy
    redirect_to achievements_url
  end

  private

  def achievement_params
    params.require(:achievement).permit(:title, :description, :privacy, :featured, :cover_image)
  end

  def owners_only
    @achievement = Achievement.find(params[:id])
    if current_user != @achievement.user
      redirect_to achievements_url
    end
  end 
end

app_for_testing/i-rock/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app_for_testing/i-rock/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app_for_testing/i-rock/app/helpers/application_helper.rb
module ApplicationHelper
end

app_for_testing/i-rock/app/views/achievements/new.html.erb
<%= simple_form_for @achievement do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :privacy, collection: Hash[Achievement.privacies.map { |k, v| [k.split("_").first.capitalize, k] }] %>
  <%= f.input :featured, label: "Featured achievement" %>
  <%= f.input :cover_image, as: :file %>

  <%= f.submit "Create Achievement", class: "btn btn-primary" %>
<% end %>

app_for_testing/i-rock/app/views/achievements/show.html.erb
<h1><%= @achievement.title %></h1>
<div>
  <%= @achievement.description_html.html_safe %>
</div>

app_for_testing/i-rock/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IRock</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">I Rock</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to 'New Achievement', new_achievement_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container-fluid">
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>
    </div>
  </body>
</html>

app_for_testing/i-rock/app/views/welcome/index.html.erb
<h1>Welcome</h1>